version: '3'

networks:
  backend:
    driver: bridge

services:
  db:
    build: ./dockerfiles/db
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/0.1.0
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=pappap
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    networks:
      - backend

  app:
    build:
      dockerfile: ./dockerfiles/app/Dockerfile
      context: .
    command: "bin/pappap start"
    environment:
      - DATABASE_URL=ecto://postgres:postgres@db/pappap
      - SECRET_KEY_BASE=tIQIht+gvi3rto8AHxzjr7WfqltNPBXWb4HnYzBS/tw0vBldMvSsxFe1rdpoOkYc
    ports:
      - 4001:4001
    tty: true
    networks:
      - backend
