-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg4Eg9WTD8AnGoamxm
HGf9VHKjZ0fxnuNOo0NQ1+0sryqgCgYIKoZIzj0DAQehRANCAAQgYpXmN+S/nAIC
zh4O1R6H3CdbW6ciLuEyhE2HgFVZDzkouOfPsXhMi9lzyuUeTnX/dSZxa+c/3kn2
76clixhm
-----END PRIVATE KEY-----